### ISSUE TITLE
Wish: Preserve last 13 years commit history

### ISSUE THREAD

**Issue by markstos** [dnmfarrell/Data-FormValidator#2]
I've converted the commit history from darcs to Git and published it here:

https://github.com/markstos/Data-FormValidator

For further bug hunting, the history could be helpful to have. This repo could be forked, and then the changes already here rebased back on top of it.

The commit history notes that it was briefly maintained in "Arch" before moving to "darcs".  Git was not even released until later.

Data::FormValidator itself started as a fork of HTML::FormValidator, written by a developer who disappeared.

For a long time I had wanted to do a rewrite that stripped out a lot of the legacy code that's not recommended to be used and some of the bad defaults that were kept for backcompat. 

One old idea that might be worth making new again: To the extent that DFV profiles are declarative, they could be expressed in data structures and not code. As a data structure, the validation profile could be expressed in JSON instead of in Perl. And as a JSON data structure, the same profile could be used be both for frontend form validation in JavaScript as well as backend validation.

These days, maybe even some of the procedural validation could be compiled to JavaScript. 

In 2010, I attempted a version of this idea with https://metacpan.org/pod/Data::FormValidator::ErrMsgs::JavaScript which never caught on.

I currently have a job doing Node.js and no longer user Perl and DFV for web work.

Good luck with the next era of Data::FormValidator!

**Comment by dnmfarrell** [comment]
Hey Mark,

This is great - thanks! I've added the commit history to the repo. Are you able to give me maintainer permissions on the CPAN repo? That way I can push a new version to CPAN.

David

**Comment by markstos** [comment]
@dnmfarrell It looks l already gave you permission on PAUSE.  "OALDERS"  ( https://github.com/oalders @oalders ) is also listed as a co-maintainer, but hasn't uploaded a new release since he had maintenanance rights.

Thank you and good luck.

**Comment by oalders** [comment]
@dnmfarrell I actually emailed you about this, but your cpan.org address bounced back to me.  Would you be able to add me as a collaborator on this repository?  You should also have co-maint on everything now, so uploading should not be a problem.

**Comment by dnmfarrell** [comment]
Thanks @markstos, you're a :star: 

@oalders Oof maybe my cpan email is not configured, sorry about that. Thanks for the heads up. I've made you a collaborator. I just released 4.82, which was basically a TLC maintenance update.
